### PR TITLE
ListPropertyInteractor implementation

### PR DESCRIPTION
**Pull request by jliqian**
Implemented use case for listing properties

### CODE REVIEW

**Comment by jliqian** [comment]
Moved all entities into entities package (for good architecture) in the future PropertyManager content should be moved into PropertyListingGateway

**Review by SMalla03 — DISMISSED** [review]
Looks fine. I have added a login interactor and a gateway for it that may need to be refactored to fit into these packages. These 2 classes have not been pull requested yet though as I am still working on it.

**Review by Omar-AlJaljuli — DISMISSED** [review]
Its good that you moved all the entities into one package, but there is still some more work all of us need to do to make the architecture better.

**Review by Rakan1837 — DISMISSED** [review]
All changes are valid, approved.

**Pull request merged**
