### PR TITLE
Feature 1 Update

### PR DESCRIPTION
**Pull request by SMalla03**

### CODE REVIEW

**Review by ZeinSulayman — DISMISSED** [review]
Good setup for the User and LoginManager Class however can you make a few changes before you pull.
User Class:
- add an instance attribute called ID which is a unique string that relates to each user instance. This id is gonna be the key for the mapping in the UserListing that links to the details of each User.
- make it so the default value for the hiredRealtor attribute is null. After all, Users will start without a hired realtor.
That's all I can think of for now.

**Comment by SMalla03** [comment]
> Good setup for the User and LoginManager Class however can you make a few changes before you pull. User Class:
> 
> * add an instance attribute called ID which is a unique string that relates to each user instance. This id is gonna be the key for the mapping in the UserListing that links to the details of each User.
> * make it so the default value for the hiredRealtor attribute is null. After all, Users will start without a hired realtor.
>   That's all I can think of for now.

Resolved issues listed above

**Review by KyleVav — APPROVED** [review]
Looks good. For clean architecture it's a little unclear what layer LoginManager is in since it seems to have methods for use cases like an interactor.

**Review by ZeinSulayman — APPROVED** [review]
Looks good.

**Review by Rakan1837 — APPROVED** [review]
Satisfied

**Pull request merged**
