### PR TITLE
Feature 6

### PR DESCRIPTION
**Pull request by ZeinSulayman**
This is the code for feature 6 which is the use case that accesses the page of a single interactor. Just the backend done to output a property from the database when given a String propertyID.

### CODE REVIEW

**Review by SMalla03 — DISMISSED** [review]
Good to merge

**Review by Rakan1837 — APPROVED** [review]
Done

**Review by Smonzer — COMMENTED** [review]
Looks good to merge.

**Review by Smonzer — DISMISSED** [review]

**Review by SMalla03 — APPROVED** [review]
All good

**Review by SMalla03 — APPROVED** [review]
all good

**Review by Rakan1837 — APPROVED** [review]
Done

**Pull request merged**
