### PR TITLE
Feature 2 buyer interactions

### PR DESCRIPTION
**Pull request by KyleVav**

### CODE REVIEW

**Review by SMalla03 — DISMISSED** [review]
all good

**Comment by jliqian** [comment]
good for merge

**Review by jliqian — APPROVED** [review]

**Review by SMalla03 — APPROVED** [review]
All good. Purely for clean architecture, maybe rename the package for the GUIs as View or View Model

**Comment by ZeinSulayman** [comment]
Everything looks fine.

**Review by ZeinSulayman — APPROVED** [review]
Everything looks good.

**Review by Rakan1837 — APPROVED** [review]
Satisfied

**Pull request merged**
