### PR TITLE
Feature 1 user login management system update

### PR DESCRIPTION
**Pull request by SMalla03**
Finished LoginInteractor for now, created Presenter package and created an output boundary for the LoginInteractor.

### CODE REVIEW

**Review by jliqian — APPROVED** [review]
looks good

**Review by KyleVav — APPROVED** [review]
Looks good to merge.

**Review by Rakan1837 — APPROVED** [review]
All changes are valid and approved.

**Review by ZeinSulayman — APPROVED** [review]
Good improvements made from last time. This looks good to merge.

**Pull request merged**
