### PR TITLE
Feature 8 in app messaging system

### PR DESCRIPTION
**Pull request by Smonzer**
Created the messenger class and made minor changes to the User class.

### CODE REVIEW

**Comment by jliqian** [comment]
I think for the default user constructor there should still be an option to create a user instance without a realtor, ie setting the value to null.
Messenger array inside a new user should probably be instantiated as the user instance is created.

**Review by jliqian — DISMISSED** [review]

**Review by SMalla03 — DISMISSED** [review]
Remember to update constructor calls in other classes after you add arguments to User class constructors

**Comment by jliqian** [comment]
Would be best to have a default user constructor that instantiates a Message arraylist, without taking in an existing Messenger

**Review by Rakan1837 — APPROVED** [review]
Approved

**Review by Rakan1837 — APPROVED** [review]
?

**Review by Omar-AlJaljuli — APPROVED** [review]
This looks like a good implementation of the back end for the in-app messaging system. Just implement the MessageManager for the next push on this branch.

**Review by ZeinSulayman — APPROVED** [review]
Make sure to add the database interactions before you merge

**Pull request merged**
