### PR TITLE
Feature 9 hiring realtor

### PR DESCRIPTION
**Pull request by eric897**

### CODE REVIEW

**Review by jliqian — DISMISSED** [review]
Looks good to merge, maybe change the interactor name to be more informative

**Review by ZeinSulayman — DISMISSED** [review]
Nice work, looks good to merge.

**Review by Rakan1837 — APPROVED** [review]
Approved

**Review by Omar-AlJaljuli — CHANGES_REQUESTED** [review]
This is good just pull the current main file so that there wont be any conflicts

**Review by jliqian — APPROVED** [review]
looks good

**Pull request merged**
