### PR TITLE
Feature 5 seller review

### PR DESCRIPTION
**Pull request by CivlisedOctopus**
The pull request contains the majority of the changes to the project classes (use case and entities) that are needed for Feature 6. This pull request is important because it makes sure that the entity files are the same as the ones written by my group members, making it sync into the overall project better.

### CODE REVIEW

**Review by ZeinSulayman — DISMISSED** [review]
Great work.

**Review by SMalla03 — APPROVED** [review]
Looks good

**Review by Rakan1837 — APPROVED** [review]
Satisfied

**Review by Rakan1837 — APPROVED** [review]
Done

**Review by ZeinSulayman — APPROVED** [review]
Good work, looks fine to merge.

**Comment by Smonzer** [comment]
looks good to merge!

**Review by Smonzer — APPROVED** [review]
done!

**Pull request merged**
