### PR TITLE
Feature 2 buyer interactions

### PR DESCRIPTION
**Pull request by KyleVav**
Added presenters/screens and screens with MVP (without controller) pattern.

### CODE REVIEW

**Review by jliqian — DISMISSED** [review]
currently failing autograder due to changes in main branch from everyone's pulls, 
Review.java, Feature4Interactor.java, AccessSinglePropertyInteractor.java (probably remove this file), LoginPageController (also probably remove this file) triggering errors

**Review by jliqian — APPROVED** [review]
Fixed the conflicts with main, commented out anything that was causing errors so everyone's code should still be intact. branch 2 runs, not sure what will happen when merged with main

**Review by SMalla03 — APPROVED** [review]
ALl good. However lowercase package names created conflicts for me because it didn't match the package names in my repo so you may want to refactor to fix that.

**Comment by eric897** [comment]
look good

**Pull request merged**
